POST http://localhost:3000/books
Content-Type: application/json

{
    "name": "3d",
    "author": "Ada",
    "description": "retyu ryrtyrtyrty rtyrtyrt",
    "numberOfPages": 200,
    "price": 1000,
    "availability": true
  }